version: '2.0'

services:
    api-nginx:
        image: "nginx:latest"
        depends_on:
            - api-php
        container_name: "api-nginx"
        ports:
                - "80:80"
        volumes:
            - "./data/logs:/var/log"
            - "${VHOSTS}:/home/vhosts"
            - "./containers/nginx/config:/etc/nginx/conf.d"

    api-db:
        image: mariadb:10.4.8
        restart: on-failure
        ports:
            - "3306:3306"
        container_name: "api-db"
        volumes:
            - "${MYSQL_DATA}:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"

    api-php:
        build:
            context: ./containers/php
        container_name: "api-php"
        expose:
            - "9000"
            - "9001"
        ports: 
            - "8080:8080"
            - "8081:8081"
        extra_hosts:
            - "${URL_SITE}:${HOST_IP}"

        volumes:
            - "./data/logs/php:/var/log/php"
            - "${VHOSTS}:/home/vhosts"
